### PR TITLE
Fix #212: unsupported expression InList

### LINKED ISSUE #212: `.schema` command crashes because of unsupported `InList` expression
```
$ cargo run testing/testing.db
Welcome to Limbo SQL shell!
> .schema
Error: Error querying schema: Parse error: unsupported expression: InList { lhs: Id(Id("type")), not: false, rhs: Some([Literal(String("'table'")), Literal(String("'index'"))]) }
```

### PR DESCRIPTION
**Pull request by jussisaurio**

### CODE REVIEW

File: cli/main.rs [hunk 1]
```diff
@@ -168,7 +168,7 @@ fn display_schema(
             table_name
         ),
         None => String::from(
-            "SELECT sql FROM sqlite_schema WHERE type IN ('table', 'index') AND name NOT LIKE 'sqlite_%' ORDER BY type, name"
+            "SELECT sql FROM sqlite_schema WHERE type IN ('table', 'index') AND name NOT LIKE 'sqlite_%'"
```
Comment (penberg) [inline cli/main.rs:171]: Why did you drop the ORDER BY?

Comment (jussisaurio) [reply cli/main.rs:171]: Because `test-sqlite` fails if they are ordered according to name. I made an (unverified) assumption that they are returned in insertion order

Comment (jussisaurio) [reply cli/main.rs:171]: I originally had the test expected output match what `limbo` outputted, but `test_sqlite` failed: `limbo` was outputting `CREATE TABLE products` first (because p < u), while `sqlite3` was outputting `CREATE TABLE users` first.
